name: note-service
image: docker.pkg.github.com/tuuturu/eme-notes-service/notes-service
version: 0.0.10
imagePullSecret: gpkg-pull-token

url: https://note-service.eme.tuuturu.org
port: 3000

environment:
  VUE_APP_BASE_URL: https://note-service.eme.tuuturu.org
  GATEKEEPER_URL: https://gatekeeper.eme.tuuturu.org
